# K Nearest Neighbors

## Machine Learning

***

https://www.ibm.com/topics/machine-learning

https://www.ibm.com/topics/artificial-intelligence

https://www.ibm.com/topics/supervised-learning

https://www.ibm.com/topics/unsupervised-learning

In [2]:
# Data frames.
import pandas as pd

# Machine Learning.
import sklearn as sk

## scikit-learn

https://scikit-learn.org/stable/getting_started.html

***

In [3]:
# Get the type of an Integer literals.
i = 1
type(i)

int

In [4]:
# Get the type of a Float literals.
f = 1.0
type(f)

float

In [5]:
from sklearn.ensemble import RandomForestClassifier
# https://www.datacamp.com/tutorial/random-forests-classifier-python

clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],  # 2 samples, 3 features (rows & columns), this could be the iris dataaset with 3 samples and 4 features
     [11, 12, 13]]
# y is the traget value. The first value (0) corresponds to first row (1,2,3) and second value (1) corresponds to the 
# second row (11,12,13)
y = [0, 1]  # classes of each sample to train the classifier
clf.fit(X, y) #Training

RandomForestClassifier(random_state=0)

In [6]:
# Predict
clf.predict(X) # Testing it on the same data as it was trained on

array([0, 1])

In [7]:
clf.predict([[4, 5, 6], [14, 15, 16]]) # Testing it with different data

array([0, 1])

## kNN in scikit-learn

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv

***

In [9]:
# Load penguins data set.
df = pd.read_csv('../data/penguins.csv')

# Show.
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [10]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

In [11]:
# The X values.
X = df[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]

# Show.
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
3               NaN            NaN                NaN          NaN
4              36.7           19.3              193.0       3450.0
..              ...            ...                ...          ...
339             NaN            NaN                NaN          NaN
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[344 rows x 4 columns]

In [12]:
# X is a data frame.
type(X)

pandas.core.frame.DataFrame

In [13]:
# Turn X into a numpy array.
X.to_numpy()

array([[  39.1,   18.7,  181. , 3750. ],
       [  39.5,   17.4,  186. , 3800. ],
       [  40.3,   18. ,  195. , 3250. ],
       ...,
       [  50.4,   15.7,  222. , 5750. ],
       [  45.2,   14.8,  212. , 5200. ],
       [  49.9,   16.1,  213. , 5400. ]])

In [14]:
# y values.
y = df['sex']

# Show.
y

0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...  
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: object

In [15]:
# Fit the data.
# Give an error, uncomment below to see it.
clf.fit(X, y)

ValueError: Input X contains NaN.
KNeighborsClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

### NaN

https://pandas.pydata.org/docs/user_guide/missing_data.html

https://docs.python.org/3/library/math.html

https://en.wikipedia.org/wiki/NaN

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html#pandas.DataFrame.dropna

In [16]:
# Look for NaNs
df.isna()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      False   False           False          False              False   
1      False   False           False          False              False   
2      False   False           False          False              False   
3      False   False            True           True               True   
4      False   False           False          False              False   
..       ...     ...             ...            ...                ...   
339    False   False            True           True               True   
340    False   False           False          False              False   
341    False   False           False          False              False   
342    False   False           False          False              False   
343    False   False           False          False              False   

     body_mass_g    sex  
0          False  False  
1          False  False  
2          False  False  
3           True   True  
4          False  False  
..           ...    ...  
339         True   True  
340        False  False  
341        False  False  
342        False  False  
343        False  False  

[344 rows x 7 columns]

In [17]:
# Drop rows with NaNs (anywhere).
df_nona = df.dropna()

# Show.
df_nona

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
4         3450.0  FEMALE  
5         3650.0    MALE  
..           ...     ...  
338       4925.0  FEMALE  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[333 rows x 7 columns]

In [18]:
# The X values.
X = df_nona[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]

# Show.
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
4              36.7           19.3              193.0       3450.0
5              39.3           20.6              190.0       3650.0
..              ...            ...                ...          ...
338            47.2           13.7              214.0       4925.0
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[333 rows x 4 columns]

In [19]:
# y values.
y = df_nona['sex']

# Show.
y

0        MALE
1      FEMALE
2      FEMALE
4      FEMALE
5        MALE
        ...  
338    FEMALE
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 333, dtype: object

In [21]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

# Fit the data.
clf.fit(X, y)

KNeighborsClassifier()

In [22]:
# The first row
df_nona.iloc[0]

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       MALE
Name: 0, dtype: object

In [23]:
# The first row of X.
X.iloc[0]

bill_length_mm         39.1
bill_depth_mm          18.7
flipper_length_mm     181.0
body_mass_g          3750.0
Name: 0, dtype: float64

In [24]:
# Quick check that the classifier correctly predicts first X sample.
clf.predict(X.iloc[:1])

array(['MALE'], dtype=object)

In [25]:
# The actual output for the first sample.
y.iloc[0]

'MALE'

## WHat is kNN?

NB: There is a mistake in Minkowski distance:

https://www.ibm.com/topics/knn

***