# K Nearest Neighbors

## Machine Learning

***

https://www.ibm.com/topics/machine-learning

https://www.ibm.com/topics/artificial-intelligence

https://www.ibm.com/topics/supervised-learning

https://www.ibm.com/topics/unsupervised-learning

In [87]:
# Data frames.
import pandas as pd

# Machine Learning.
import sklearn as sk

# https://www.datacamp.com/tutorial/random-forests-classifier-python
from sklearn.ensemble import RandomForestClassifier

## scikit-learn

https://scikit-learn.org/stable/getting_started.html

***

In [88]:
# Get the type of an Integer literals.
i = 1
type(i)

int

In [89]:
# Get the type of a Float literals.
f = 1.0
type(f)

float

In [90]:
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],  # 2 samples, 3 features (rows & columns), this could be the iris dataaset with 3 samples and 4 features
     [11, 12, 13]]
# y is the traget value. The first value (0) corresponds to first row (1,2,3) and second value (1) corresponds to the 
# second row (11,12,13)
y = [0, 1]  # classes of each sample to train the classifier
clf.fit(X, y) #Training

RandomForestClassifier(random_state=0)

In [91]:
# Predict
clf.predict(X) # Testing it on the same data as it was trained on

array([0, 1])

In [92]:
clf.predict([[4, 5, 6], [14, 15, 16]]) # Testing it with different data

array([0, 1])

## kNN in scikit-learn

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

https://github.com/mwaskom/seaborn-data/blob/master/penguins.csv

***

In [93]:
# Load penguins data set.
df = pd.read_csv('../data/penguins.csv')

# Show.
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
3            NaN     NaN  
4         3450.0  FEMALE  
..           ...     ...  
339          NaN     NaN  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[344 rows x 7 columns]

In [94]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

In [95]:
# The X values.
X = df[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]

# Show.
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
3               NaN            NaN                NaN          NaN
4              36.7           19.3              193.0       3450.0
..              ...            ...                ...          ...
339             NaN            NaN                NaN          NaN
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[344 rows x 4 columns]

In [96]:
# X is a data frame.
type(X)

pandas.core.frame.DataFrame

In [97]:
# Turn X into a numpy array.
X.to_numpy()

array([[  39.1,   18.7,  181. , 3750. ],
       [  39.5,   17.4,  186. , 3800. ],
       [  40.3,   18. ,  195. , 3250. ],
       ...,
       [  50.4,   15.7,  222. , 5750. ],
       [  45.2,   14.8,  212. , 5200. ],
       [  49.9,   16.1,  213. , 5400. ]])

In [98]:
# y values.
y = df['sex']

# Show.
y

0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...  
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: object

In [99]:
# Fit the data.
# Give an error, does not accept NaN. Uncomment below to see it.
#clf.fit(X, y)

### NaN

https://pandas.pydata.org/docs/user_guide/missing_data.html

https://docs.python.org/3/library/math.html

https://en.wikipedia.org/wiki/NaN

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html#pandas.DataFrame.dropna

In [100]:
# Look for NaNs
df.isna()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0      False   False           False          False              False   
1      False   False           False          False              False   
2      False   False           False          False              False   
3      False   False            True           True               True   
4      False   False           False          False              False   
..       ...     ...             ...            ...                ...   
339    False   False            True           True               True   
340    False   False           False          False              False   
341    False   False           False          False              False   
342    False   False           False          False              False   
343    False   False           False          False              False   

     body_mass_g    sex  
0          False  False  
1          False  False  
2          False  False  
3           True   True  
4          False  False  
..           ...    ...  
339         True   True  
340        False  False  
341        False  False  
342        False  False  
343        False  False  

[344 rows x 7 columns]

In [101]:
# Drop rows with NaNs (anywhere).
df_nona = df.dropna()

# Show.
df_nona

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    MALE  
1         3800.0  FEMALE  
2         3250.0  FEMALE  
4         3450.0  FEMALE  
5         3650.0    MALE  
..           ...     ...  
338       4925.0  FEMALE  
340       4850.0  FEMALE  
341       5750.0    MALE  
342       5200.0  FEMALE  
343       5400.0    MALE  

[333 rows x 7 columns]

In [102]:
# The X values.
X = df_nona[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]

# Show.
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
0              39.1           18.7              181.0       3750.0
1              39.5           17.4              186.0       3800.0
2              40.3           18.0              195.0       3250.0
4              36.7           19.3              193.0       3450.0
5              39.3           20.6              190.0       3650.0
..              ...            ...                ...          ...
338            47.2           13.7              214.0       4925.0
340            46.8           14.3              215.0       4850.0
341            50.4           15.7              222.0       5750.0
342            45.2           14.8              212.0       5200.0
343            49.9           16.1              213.0       5400.0

[333 rows x 4 columns]

In [103]:
# y values.
y = df_nona['sex']

# Show.
y

0        MALE
1      FEMALE
2      FEMALE
4      FEMALE
5        MALE
        ...  
338    FEMALE
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 333, dtype: object

In [104]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

# Fit the data.
clf.fit(X, y)

KNeighborsClassifier()

In [105]:
# The first row
df_nona.iloc[0]

species                 Adelie
island               Torgersen
bill_length_mm            39.1
bill_depth_mm             18.7
flipper_length_mm        181.0
body_mass_g             3750.0
sex                       MALE
Name: 0, dtype: object

In [106]:
# The first row of X.
X.iloc[0]

bill_length_mm         39.1
bill_depth_mm          18.7
flipper_length_mm     181.0
body_mass_g          3750.0
Name: 0, dtype: float64

In [107]:
# Quick check that the classifier correctly predicts first X sample.
clf.predict(X.iloc[:1])

array(['MALE'], dtype=object)

In [108]:
# The actual output for the first sample.
y.iloc[0]

'MALE'

## What is kNN?

NB: There is a mistake in Minkowski distance:

https://www.ibm.com/topics/knn

***

In [130]:
# Point a.
a = X.iloc[0]

# Show a.
a

bill_length_mm         39.1
bill_depth_mm          18.7
flipper_length_mm     181.0
body_mass_g          3750.0
Name: 0, dtype: float64

In [110]:
# Point b.
b = X.iloc[1]

# Show b.
b

bill_length_mm         39.5
bill_depth_mm          17.4
flipper_length_mm     186.0
body_mass_g          3800.0
Name: 1, dtype: float64

In [111]:
# Differences - straight forward subtraction.
a - b

bill_length_mm       -0.4
bill_depth_mm         1.3
flipper_length_mm    -5.0
body_mass_g         -50.0
dtype: float64

In [112]:
# Total difference.
(a - b).sum()

-54.099999999999994

In [113]:
# Differences - straight forward subtraction.
b - a

bill_length_mm        0.4
bill_depth_mm        -1.3
flipper_length_mm     5.0
body_mass_g          50.0
dtype: float64

In [114]:
# Total difference.
(b - a).sum()

54.099999999999994

In [115]:
# Differences - absolute values.
(b - a).abs()

bill_length_mm        0.4
bill_depth_mm         1.3
flipper_length_mm     5.0
body_mass_g          50.0
dtype: float64

In [116]:
# Total difference - absolute values.
(b - a).abs().sum()

56.7

In [117]:
# A more common distance (Euclidean distance - Pythagoras theorem).
((b - a)**2).sum()**0.5

50.26778292306117

## Evaluation

***

In [118]:
# Ask the classifier to predict the outputs for the training set inputs.
# (Usually a bad idea.)
clf.predict(X)

array(['MALE', 'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE',
       'FEMALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE',
       'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE',
       'MALE', 'FEMALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE',
       'FEMALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE',
       'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE',
       'MALE', 'FEMALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE', 'M

In [119]:
# Compare to the expected outputs.
clf.predict(X) == y

0       True
1       True
2       True
4       True
5      False
       ...  
338     True
340     True
341     True
342    False
343     True
Name: sex, Length: 333, dtype: bool

In [120]:
# Count of correct values (true becomes 1 and false become 0)
(clf.predict(X) == y).sum()

276

In [121]:
# Total number of cases.
X.shape[0]

333

In [122]:
# Proportion of correct predictions.
(clf.predict(X) == y).sum() / X.shape[0]

0.8288288288288288

In [123]:
# Keep some samples back for testing, train on the others.
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, y)

In [124]:
# Training inputs (randomly selected).
X_train

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
281            46.2           14.9              221.0       5300.0
108            38.1           17.0              181.0       3175.0
45             39.6           18.8              190.0       4600.0
62             37.6           17.0              185.0       3600.0
241            45.1           14.5              215.0       5000.0
..              ...            ...                ...          ...
124            35.2           15.9              186.0       3050.0
223            50.0           15.2              218.0       5700.0
117            37.3           20.5              199.0       3775.0
66             35.5           16.2              195.0       3350.0
266            45.5           13.9              210.0       4200.0

[249 rows x 4 columns]

In [125]:
# Training outputs (randomly selected).
y_train

281      MALE
108    FEMALE
45       MALE
62     FEMALE
241    FEMALE
        ...  
124    FEMALE
223      MALE
117      MALE
66     FEMALE
266    FEMALE
Name: sex, Length: 249, dtype: object

In [126]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

# Fit the data.
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [127]:
# Predict based on test set.
clf.predict(X_test)

array(['MALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE',
       'MALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE', 'FEMALE',
       'MALE', 'FEMALE', 'MALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE',
       'MALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE', 'MALE', 'FEMALE',
       'MALE', 'FEMALE', 'MALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE', 'FEMALE', 'FEMALE',
       'MALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'MALE', 'FEMALE', 'MALE', 'MALE', 'MALE', 'MALE',
       'FEMALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE', 'MALE',
       'MALE', 'MALE', 'MALE', 'FEMALE', 'FEMALE', 'FEMALE', 'FEMALE',
       'FEMALE', 'FEMALE', 'MALE', 'MALE', 'MALE', 'MALE', 'FEMALE'],
      dtype=object)

In [128]:
# Proportion of correct classifications on test set.
(clf.predict(X_test) == y_test).sum() / X_test.shape[0]

0.75

### Cross-validation

https://scikit-learn.org/stable/modules/cross_validation.html

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html
***

In [129]:
# Create a new instance of a classifier.
clf = sk.neighbors.KNeighborsClassifier()

# Run cross-validation with five folds.
sk.model_selection.cross_val_score(clf, X, y) # default is 5 folds (cv=5)

array([0.76119403, 0.7761194 , 0.71641791, 0.74242424, 0.72727273])

***

## End